Feature next auth
eduardodiaz110/Comment-Section pull request #3
Opened 2023-08-30 21:00 UTC by eduardodiaz110

2023-09-05 05:44 UTC, eKoh951 requested changes
Se ve bien en general, solo le hacen falta varias buenas practicas

2023-09-05 05:44 UTC, eKoh951 commented on .env
> +NEXTAUTH_SECRET =jogmreirg
Los archivos `.env` no se commitean en git, porque estos ya cuando los subes a github, quedan expuestos a las personas que tengan acceso a github, es como si subieras tu archivo con contrasenias a la nube.

Ahora por ejemplo, cuando borras este archivo `.env` y comitteas esto, cualquier persona podria devolverse al commit donde exisitio el archivo `.env` y recuperar el archivo, esto es una vulnerabilidad en tu repositorio, por eso los archivos `.env` y cualquier informacion delicada no deben de commitearse.

Por lo general se crea un archivo `.env.example` que es un ejemplo de tu archivo `.env` para que otros desarrolladores sepan que variables de entorno tienen que guardar.

Una variable de entorno es `MONGODB_URI` cuyo valor es `mongodb+srv://eduardogonzalez:fMHU5Ms0f6DdbZaG@cluster0.peicyih.mongodb.net/comments`

En este string, este es tu usuario: `eduardogonzalez` y esta tu contrasenia `fMHU5Ms0f6DdbZaG`, con esos valores me puedo conectar a tu base de datos, borrarla, corromperla, etc.

2023-09-05 05:44 UTC, eKoh951 commented on app/api/comments/route.js
> +  console.log("request", content, replyingTo, score, userId);
Asegurate de remover los `console.log` antes de mergear a `main`

2023-09-05 05:44 UTC, eKoh951 commented on app/functions/register.tsx
> +    const res = await fetch("http://localhost:3000/api/auth/signup", {
Todos tus `http://localhost:3000` cambialos a tu variable de entorno `NEXTAUTH_URL`, este codigo como lo tienes no deberia funcionar en el deployment ya en Vercel.

Essto deberia estar asi:

```typescript
const res = await fetch(`${process.env.NEXTAUTH_URL}/api/auth/signup`, {
...
````

Fijate que uso template string ( ` )

2023-09-05 05:44 UTC, eKoh951 commented on app/functions/textBox.tsx
Mira, esto se puede refactorizar a esto:

```typescript
const bodyData= {
  content,
  score: 0,
  userId,
};

if (replyTo) {
  bodyData.replyingTo = replyTo;
}

````

Aunque typescript se va a quejar de que en `bodyData` no existe la propiedad `replyingTo`, entonces hay que crear una interfaz:

````typescript
interface CommentData {
  content: string;
  score: number;
  userId: string;
  replyingTo?: string;
}

const bodyData: CommentData = {
....
````

2023-09-05 05:44 UTC, eKoh951 commented on app/login/page.tsx
> +export default function LogInPage() {
Mira, vamos a refactorizar este componente a:

```typescript
import { Box, Button, TextField, Typography } from "@mui/material";
import React, { useState } from "react";
import { signIn } from "next-auth/react";
import { useRouter } from "next/router";

export default function LogInPage() {
  const Router = useRouter();

  const [formData, setFormData] = useState({
    email: "",
    password: "",
    username: "",
  });

  const [error, setError] = useState("");

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = event.target;
    setFormData((prevData) => ({
      ...prevData,
      [name]: value,
    }));
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    const res = await signIn("credentials", {
      email: formData.email,
      password: formData.password,
      redirect: false,
    });

    if (res?.error) {
      return setError(res.error as string);
    }

    if (res?.ok) {
      return Router.push("/dashboard");
    }
  };

  return (
    <div>
      {error && (
        <Box
          sx={{
            display: "flex",
            backgroundColor: "red",
            alignItems: "center",
            justifyContent: "center",
            height: "35px",
          }}
        >
          <Typography color={"white"} variant="body1">
            {error}
          </Typography>
        </Box>
      )}
      <Box
        sx={{
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <h1>Iniciar Sesion</h1>
      </Box>
      <Box
        sx={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          height: "80vh",
          gap: "10px",
        }}
      >
        <form onSubmit={handleSubmit} style={{ width: "40%" }}>
          <Box
            sx={{
              display: "flex",
              alignContent: "center",
              justifyContent: "center",
              flexDirection: "column",
              gap: "10px",
            }}
          >
            <TextField
              type="email"
              placeholder="email"
              name="email"
              fullWidth
              onChange={handleChange}
              value={formData.email}
            />
            <TextField
              type="password"
              placeholder="password"
              name="password"
              fullWidth
              onChange={handleChange}
              value={formData.password}
            />
            <Button
              variant="contained"
              sx={{ width: "100%", height: "50px" }}
              type="submit"
            >
              Iniciar Sesion
            </Button>
          </Box>
        </form>
      </Box>
    </div>
  );
}
```

Inicializamos el `formData`:
```typescript
  const [formData, setFormData] = useState({
    email: "",
    password: "",
    username: "",
  });
  
  ```
  
  Y este `formData` tiene los valores de todos los inputs del form, y usamos 1 solo estado (de useState) para controlar la informacion y no un estado para cada input, asi nos ahorramos codigo y es mas flexible para que puedas agregar varios inputs.

Fijate como queda el `handleChange`:

```typescript
  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = event.target;
    setFormData((prevData) => ({
      ...prevData,
      [name]: value,
    }));
  };
````

Queda mas sencillo porque ahora el cambio de los inputs esta siendo manejado desde el form, no desde cada input, asi es mejor para que no tengas que agregar un nuevo estado por cada input que agregas y es una mejor practica.

Y si te fijas ahora los `<TextFields />` estan agarrando su valor desde `formData`:

```typescript
            <TextField
              type="password"
              placeholder="password"
              name="password"
              fullWidth
              onChange={handleChange}
              value={formData.password}
            />
````

2023-09-05 05:44 UTC, eKoh951 commented on app/login/page.tsx
> +    console.log(res);
Asegurate de borrar el `console.log` antes de ir a produccion

2023-09-05 05:44 UTC, eKoh951 commented on app/page.tsx
> +      {/* <pre>{JSON.stringify(comments, null, 2)}</pre> */}
Asegurate de borrar codigo sin usar antes de ir a produccion

2023-09-05 05:44 UTC, eKoh951 commented on app/register/page.tsx
> +export default function RegisterPage() {
En vez de practicamente repetir `/register` y `/login`, crea un componente que se llame `<Sign />` con una prop que sea `register: boolean`, si es `true` significa que es la page de `/register`, si es false, significa que es la page de `/login`.

2023-09-05 13:23 UTC, MarcoSoteloJ approved these changes

2023-09-06 22:59 UTC, eduardodiaz110 commented on app/register/page.tsx
> +export default function RegisterPage() {
me gustaria ayuda para hacer este cambio, pq tanto Register como Login, tienen diferentes cosillas

2023-09-06 23:12 UTC, merged